### ISSUE TITLE
MrEntertainment Thank you.

### ISSUE THREAD

**Issue by doser5** [MrEntertainment/backupREPO#2]
MrEntertainment account is an imposter sadly :(

**Comment by DjDiabolik** [comment]
You are absolutely sure it's the real back ? Here on Github it's exist so many fork....... it's could possibly someone has register an account whit same name.

I will be totally sure only when i see the site back totally online or somethigs on twitter or telegram group or similar.............

I hope however it is to be wrong this my affermation :)

**Comment by DjDiabolik** [comment]
@doser5 have you find some confirmation ?

plugin.program.indigo....... it's present.

It's problably only a TVA forks.
